#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""
Copyright (c) 2013, David Silva
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
        names of its contributors may be used to endorse or promote products
        derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import adblock_http

# hosts file
HOSTS_FILE = "/etc/hosts"

# MVPS content filters
MVPS_START_STR = "# [Start of entries generated by MVPS HOSTS]"
MVPS_END_STR = "# [end of entries generated by MVPS HOSTS]"

def __read_and_filter_hosts_file():
    """
    Reads and filters the hosts file contents
    with the MVPS related contents
    """
    read_mvps = False
    data = ''
    with open(HOSTS_FILE, 'r') as ofp:
        for line in ofp:
            if len(line) > 0:
                line = line.strip('\n')
                read_mvps = read_mvps or line == MVPS_START_STR
                if read_mvps and line not in (MVPS_END_STR, '#'):
                    data += line + '\n'
    size = len(data)
    return data[len(MVPS_START_STR)+1:size-1] if size > 0 else None

def read_local_hosts():
    """
    Reads the current hosts file contents
    and filters it with the related MVPS information
    """
    return __read_and_filter_hosts_file()

def read_remote_hosts():
    """
    Reads the remote MVPS hosts file contents
    """
    return adblock_http.get_remote_mvps_hosts()
